In [1]:
import matplotlib

In [2]:
main = '/g/data/fk4/wofs/current/extents'

In [3]:
import os

In [4]:
import numpy as np

In [5]:
from matplotlib import pyplot as plt

In [8]:
for folder in os.listdir(main):
    print folder

147_-041
142_-034
129_-013
128_-022
145_-015
146_-019
151_-023
116_-024
139_-021
115_-036
127_-029
122_-019
134_-018
145_-016
112_-036
126_-027
115_-022
130_-030
139_-027
133_-034
133_-030
151_-024
119_-024
140_-021
135_-027
132_-011
139_-035
134_-036
126_-032
143_-027
153_-029
134_-021
129_-027
117_-021
127_-025
130_-032
133_-036
153_-026
125_-027
151_-035
141_-024
131_-029
140_-039
135_-019
148_-020
131_-015
151_-028
125_-023
124_-012
136_-030
145_-013
138_-039
134_-019
145_-024
143_-014
140_-023
132_-022
134_-025
123_-025
123_-018
150_-028
134_-014
124_-011
131_-013
146_-044
146_-036
148_-030
135_-018
139_-022
133_-013
139_-032
142_-019
138_-017
117_-033
146_-022
140_-033
141_-036
127_-027
148_-021
127_-015
118_-028
133_-015
144_-030
129_-021
150_-026
133_-018
121_-016
142_-036
149_-043
144_-019
146_-028
138_-020
150_-037
132_-035
145_-037
151_-030
142_-027
118_-026
131_-011
148_-022
148_-032
134_-024
113_-021
115_-034
128_-030
146_-045
120_-030
126_-035
141_-028
150_-032
146_-026
1

In [10]:
tile = '120_-022'

In [11]:
tile_folder = os.path.join(main,tile)

In [12]:
t = [[1], [1]]
np.asarray(t)
np.shape(t)

(2, 1)

In [13]:
tile_folder

'/g/data/fk4/wofs/current/extents/120_-022'

In [14]:
import Image
#im=image.open('LS5_TM_WATER_120_-022_1987-09-06T01-22-31.094063.tif')

ImportError: No module named Image

In [15]:
for (dirpath,dirnames,filenames) in os.walk(tile_folder):
    for f in sorted(filenames):
        if f.endswith('.nc'):
            print f
        



LS_WATER_120_-022_1987-05-24T01-26-07_2016-01-17T01-57-57.nc


In [53]:
import netCDF4
fi = 'LS_WATER_120_-022_1987-05-24T01-26-07_2016-01-17T01-57-57.nc'

In [46]:
import os

In [54]:
t_file = os.path.join(tile_folder, fi)
print t_file


/g/data/fk4/wofs/current/extents/120_-022/LS_WATER_120_-022_1987-05-24T01-26-07_2016-01-17T01-57-57.nc


In [55]:
fh = Dataset(t_file, mode='r')

In [57]:
fh

<type 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    date_created: 2016-03-16T09:11:38.627375
    Conventions: CF-1.6
    dimensions(sizes): latitude(4000), longitude(4000), time(1270)
    variables(dimensions): int32 crs(), float64 latitude(latitude), float64 longitude(longitude), float64 time(time), int8 Data(latitude,longitude,time)
    groups: 

In [63]:
lat = fh.variables['latitude'][:]
lon = fh.variables['longitude'][:]
time = fh.variables['time'][:]

Data1 = fh.variables['Data'][:,:,1]

In [74]:
g = Data1[0:0,0:0]
np.min(Data1)

-128

In [26]:
fh = Dataset(t_file, mode='r')

IOError: No such file or directory

In [75]:
Data1

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int8)

In [80]:
(Data1 >> 7).astype(bool)

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ..., 
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]], dtype=bool)

In [84]:
from collections import namedtuple 
import numpy as np

'''bit 7 - water present Decimal value 128: 1=water present, 0=no water if all other bits zero
bit 6 - cloud Decimal value: 64: 1=pixel masked out due to cloud, 0=unmasked
bit 5 - cloud shadow Decimal value: 32: 1=pixel masked out due to cloud shadow,
0=unmasked
bit 4 - high slope Decimal value: 16: 1=pixel masked out due to high slop, 0=unmasked
bit 3 - terrain shadow Decimal value: 8: 1=pixel masked out due to terrain shadow,
0=unmasked
bit 2 - sea
Decimal value: 4: 1=pixel masked out due to being over sea,
0=unmasked
bit 1 - contiguity
Decimal value: 2: 1=pixel masked out due to lack of data contiguity,
0=unmasked
bit 0 - no data
Decimal value: 1:1=pixel masked out due to NO_DATA in NBAR
source, 0=valid data in NBAR
'''


def unpack_wofs(data):
    """Unpack an array of WOFS data to a collection of binary arrays
    of the same shape."""
    return namedtuple('WOFS', [
            'water_present', 'cloud', 'cloud_shadow', 'high_slope',
            'terrain_shadow', 'sea', 'contiguity', 'nodata'])(
        *np.unpackbits(data.astype(np.uint8)[np.newaxis], axis=0).astype(bool))    

In [86]:
dat = unpack_wofs(Data1)
dat.water_present

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ..., 
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]], dtype=bool)

In [87]:
dat.cloud

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ..., 
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]], dtype=bool)